### ISSUE TITLE
最后一个item无法收藏

### ISSUE THREAD

**Issue by BrucePhoebus** [mehaotian/hx-code-cloud#1]
![image](https://user-images.githubusercontent.com/15230068/150511491-49391230-cc80-4c32-b233-632265e6cc5b.png)
最后一个item鼠标上去不是手指，似乎是多了个遮蔽层，大概挡到浏览器的浏字上下到收藏按钮整块

**Comment by BrucePhoebus** [comment]
个人乱七八糟的插件挡住了

**Comment by mehaotian** [comment]
我看看 ，这可还行
